<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_RzyO0KoMEee96aJ4KpltLA" name="wfAgentCommission" author="Talend" bonitaVersion="7.2.3" bonitaModelVersion="7.2.0-002" configId="ACED00057400174D794469616772616D372E322E302D303032372E322E33">
    <elements xmi:type="process:Pool" xmi:id="_RzyO0aoMEee96aJ4KpltLA" name="wfAgentCommission" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Lane" xmi:id="_Rzy14aoMEee96aJ4KpltLA" name="wfAgentCommission" actor="_Rzy14KoMEee96aJ4KpltLA">
        <elements xmi:type="process:StartEvent" xmi:id="_vyXbs2KUEeaDbeg_vFJw6Q" name="Start" outgoing="_dP0X0KoNEee96aJ4KpltLA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_vyXbtGKUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vyXbtWKUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vyXbtmKUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vyXbt2KUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_14oWEKoMEee96aJ4KpltLA" name="Commission Approval" outgoing="_g1Z-cKoNEee96aJ4KpltLA" incoming="_dP0X0KoNEee96aJ4KpltLA" actor="_Rzy14KoMEee96aJ4KpltLA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_141KY6oMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_141KYaoMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_141KYKoMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_141KYqoMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_tGGTAKoYEee96aJ4KpltLA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_tGSgQKoYEee96aJ4KpltLA" name="mdm_context" content="mdm_context" type="TYPE_VARIABLE" returnType="org.talend.mdm.workflow.client.MDMContext">
              <referencedElements xmi:type="process:JavaObjectData" xmi:id="_vYkE4KoYEee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_tGR5MKoYEee96aJ4KpltLA" name="Set the user for update" content="import org.talend.mdm.workflow.client.MDMContextUser;&#xA;MDMContextUser contextUser = mdm_context.getCurrentUser();&#xA;return contextUser.getName();" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:JavaObjectData" xmi:id="_2kgHIKoYEee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_tGGTAaoYEee96aJ4KpltLA" type="JAVA_METHOD" expression="setUpdateUsername">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_141KZqoMEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_141KZ6oMEee96aJ4KpltLA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_141KaKoMEee96aJ4KpltLA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_141xcKoMEee96aJ4KpltLA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_141KaaoMEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_Dn3l4KoQEee96aJ4KpltLA" name="CommissionApproval" nColumn="2" nLine="5">
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_Dn40AKoQEee96aJ4KpltLA" documentation="Reject New Commission" name="Cancel">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Dn40AaoQEee96aJ4KpltLA" line="4"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_Dn40AqoQEee96aJ4KpltLA" name="Reject New Commission" content="Reject New Commission" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_Dn40A6oQEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <actions xmi:type="expression:Operation" xmi:id="_PsAbQKoSEee96aJ4KpltLA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_PsSvIaoSEee96aJ4KpltLA" name="mdm_context" content="mdm_context" type="TYPE_VARIABLE" returnType="org.talend.mdm.workflow.client.MDMContext">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_SBY-QKoSEee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_PsSvIKoSEee96aJ4KpltLA" name="Set Rejected Status" content="&quot;Agent/CommissionChange/ComChangeStatus#Rejected&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
                <operator xmi:type="expression:Operator" xmi:id="_PsAbQaoSEee96aJ4KpltLA" type="JAVA_METHOD" expression="setValue">
                  <inputTypes>java.lang.String</inputTypes>
                </operator>
              </actions>
            </widgets>
            <widgets xmi:type="form:TextInfo" xmi:id="_I8UiEKoQEee96aJ4KpltLA" name="AgentName">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_I8Yzg6oQEee96aJ4KpltLA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_I8W-UqoQEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_I8W-U6oQEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_I8W-UaoQEee96aJ4KpltLA" name="Get Agent Name" content="mdm_context.getValue(&quot;Agent/Firstname&quot;) + &quot; &quot; + mdm_context.getValue(&quot;Agent/Lastname&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_qVZaEKolEee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_I8W-VKoQEee96aJ4KpltLA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_I8W-UKoQEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_I8WXQaoQEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_I8VwMKoQEee96aJ4KpltLA" name="Agent Name" content="Agent Name" interpreter="GROOVY" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_I8WXQKoQEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_I8W-VaoQEee96aJ4KpltLA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_I8W-VqoQEee96aJ4KpltLA"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_I8W-V6oQEee96aJ4KpltLA"/>
                <operator xmi:type="expression:Operator" xmi:id="_I8W-WKoQEee96aJ4KpltLA" type="ASSIGNMENT" expression="="/>
              </action>
            </widgets>
            <widgets xmi:type="form:TextInfo" xmi:id="_PXBfMKoREee96aJ4KpltLA" name="CurrentCommissionCode">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_PXDUYaoREee96aJ4KpltLA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_PXBfNqoREee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_PXBfN6oREee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_PXBfNaoREee96aJ4KpltLA" name="Get Current Commission Code" content="mdm_context.getValue(&quot;Agent/CommissionCode&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_iegtcKoREee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_PXBfOKoREee96aJ4KpltLA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_PXBfNKoREee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_PXBfM6oREee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_PXBfMaoREee96aJ4KpltLA" name="Current Commission Code" content="Current Commission Code" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_PXBfMqoREee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_PXBfOaoREee96aJ4KpltLA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_PXCGQKoREee96aJ4KpltLA"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_PXCGQaoREee96aJ4KpltLA"/>
                <operator xmi:type="expression:Operator" xmi:id="_PXCGQqoREee96aJ4KpltLA" type="ASSIGNMENT" expression="="/>
              </action>
            </widgets>
            <widgets xmi:type="form:TextInfo" xmi:id="_sWNLUKoREee96aJ4KpltLA" name="NewCommissionCode">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_sWYKcKoREee96aJ4KpltLA" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_sWOZdaoREee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_sWOZdqoREee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_sWOZdKoREee96aJ4KpltLA" name="Get New Commission Code" content="mdm_context.getValue(&quot;Agent/CommissionChange/ComChangeCode&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_uBWucKolEee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_sWOZd6oREee96aJ4KpltLA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_sWOZc6oREee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_sWOZcqoREee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_sWOZcKoREee96aJ4KpltLA" name="Review New Commission Code" content="Review New Commission Code" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_sWOZcaoREee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_sWOZeKoREee96aJ4KpltLA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_sWOZeaoREee96aJ4KpltLA"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_sWOZeqoREee96aJ4KpltLA"/>
                <operator xmi:type="expression:Operator" xmi:id="_sWOZe6oREee96aJ4KpltLA" type="ASSIGNMENT" expression="="/>
              </action>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_RYy3wKoTEee96aJ4KpltLA" name="Allow">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_RY17EKoTEee96aJ4KpltLA" line="4" column="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_RYze1aoTEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_RYze1qoTEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_RYze1KoTEee96aJ4KpltLA" name="" content=""/>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_RYze16oTEee96aJ4KpltLA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_RYze06oTEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_RYze0qoTEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_RYze0KoTEee96aJ4KpltLA" name="Approve New Commission" content="Approve New Commission" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_RYze0aoTEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_RYze2KoTEee96aJ4KpltLA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_RYze2aoTEee96aJ4KpltLA"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_RYze2qoTEee96aJ4KpltLA"/>
                <operator xmi:type="expression:Operator" xmi:id="_RYze26oTEee96aJ4KpltLA" type="ASSIGNMENT" expression="="/>
              </action>
              <actions xmi:type="expression:Operation" xmi:id="_WWkZUKoTEee96aJ4KpltLA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_WWybwaoTEee96aJ4KpltLA" name="mdm_context" content="mdm_context" type="TYPE_VARIABLE" returnType="org.talend.mdm.workflow.client.MDMContext">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_W-sJQKoTEee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_WWybwKoTEee96aJ4KpltLA" name="Set Approved Status" content="&quot;Agent/CommissionChange/ComChangeStatus#Approved&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
                <operator xmi:type="expression:Operator" xmi:id="_WWkZUaoTEee96aJ4KpltLA" type="JAVA_METHOD" expression="setValue">
                  <inputTypes>java.lang.String</inputTypes>
                </operator>
              </actions>
              <actions xmi:type="expression:Operation" xmi:id="_edqcQKoTEee96aJ4KpltLA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_ed_MYaoTEee96aJ4KpltLA" name="mdm_context" content="mdm_context" type="TYPE_VARIABLE" returnType="org.talend.mdm.workflow.client.MDMContext">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_e8YYkKoTEee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_ed_MYKoTEee96aJ4KpltLA" name="Set New Commission Code" content="&quot;Agent/CommissionCode#&quot; + mdm_context.getValue(&quot;Agent/CommissionChange/ComChangeCode&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_lbOEQKoTEee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_edqcQaoTEee96aJ4KpltLA" type="JAVA_METHOD" expression="setValue">
                  <inputTypes>java.lang.String</inputTypes>
                </operator>
              </actions>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_Dn40BKoQEee96aJ4KpltLA" name="Commission Approval" content="Commission Approval" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_141KZKoMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_141KZaoMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_141xcqoMEee96aJ4KpltLA">
            <targetForm xmi:type="expression:Expression" xmi:id="_141xc6oMEee96aJ4KpltLA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_141xcaoMEee96aJ4KpltLA"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_8QX7QKoMEee96aJ4KpltLA" name="Submit Update" outgoing="_hpwzkKoNEee96aJ4KpltLA" incoming="_g1Z-cKoNEee96aJ4KpltLA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_8QYiU6oMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8QYiUaoMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8QYiUKoMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8QYiUqoMEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Iv_AIKoZEee96aJ4KpltLA" name="Submit Update" definitionId="TalendMDMContextConnector" event="ON_FINISH" definitionVersion="6.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Iv_AIaoZEee96aJ4KpltLA" definitionId="TalendMDMContextConnector" version="6.0" modelVersion="7.2.0-002">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_AIqoZEee96aJ4KpltLA" key="contextName">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_AI6oZEee96aJ4KpltLA" name="mdm_context" content="mdm_context" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_AJKoZEee96aJ4KpltLA" key="endpointUrl">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_AJaoZEee96aJ4KpltLA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_AJqoZEee96aJ4KpltLA" key="user">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_AJ6oZEee96aJ4KpltLA" name="administrator" content="administrator" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_AKKoZEee96aJ4KpltLA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_AKaoZEee96aJ4KpltLA" name="administrator" content="administrator" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_AKqoZEee96aJ4KpltLA" key="partial">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_AK6oZEee96aJ4KpltLA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_ALKoZEee96aJ4KpltLA" key="overwrite">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_ALaoZEee96aJ4KpltLA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_ALqoZEee96aJ4KpltLA" key="delete">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_AL6oZEee96aJ4KpltLA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_AMKoZEee96aJ4KpltLA" key="key">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_AMaoZEee96aJ4KpltLA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_AMqoZEee96aJ4KpltLA" key="pivot">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_AM6oZEee96aJ4KpltLA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Iv_ANKoZEee96aJ4KpltLA" key="position">
                <expression xmi:type="expression:Expression" xmi:id="_Iv_ANaoZEee96aJ4KpltLA" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8QYiVKoMEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8QYiVaoMEee96aJ4KpltLA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8QYiVqoMEee96aJ4KpltLA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8QYiWKoMEee96aJ4KpltLA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8QYiV6oMEee96aJ4KpltLA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_UzHRQKoNEee96aJ4KpltLA" name="End1" incoming="_hpwzkKoNEee96aJ4KpltLA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_UzH4U6oNEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UzH4UaoNEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UzH4UKoNEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UzH4UqoNEee96aJ4KpltLA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_BShiUKoUEee96aJ4KpltLA" path="_RzyO0aoMEee96aJ4KpltLA/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_vyXbx2KUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_vyXbyGKUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_BSiJY6oUEee96aJ4KpltLA" path="_RzyO0aoMEee96aJ4KpltLA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_BSiJYKoUEee96aJ4KpltLA" path="_RzyO0aoMEee96aJ4KpltLA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_BSiJZKoUEee96aJ4KpltLA" path="_RzyO0aoMEee96aJ4KpltLA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_BSiJYaoUEee96aJ4KpltLA" path="_RzyO0aoMEee96aJ4KpltLA/html/consultation.html"/>
      <data xmi:type="process:JavaObjectData" xmi:id="_Rz48gKoMEee96aJ4KpltLA" name="mdm_context" dataType="_vyXb62KUEeaDbeg_vFJw6Q" className="org.talend.mdm.workflow.client.MDMContext"/>
      <confirmationTemplate xmi:type="process:AssociatedFile" xmi:id="_BSiJYqoUEee96aJ4KpltLA" path="_RzyO0aoMEee96aJ4KpltLA/html/confirmation.html"/>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_vyXbyWKUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_vyXbymKUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_vyXby2KUEeaDbeg_vFJw6Q" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_vyXbzGKUEeaDbeg_vFJw6Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_vyXbzWKUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_vyXbzmKUEeaDbeg_vFJw6Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_vyXbz2KUEeaDbeg_vFJw6Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_vyXb0GKUEeaDbeg_vFJw6Q" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dP0X0KoNEee96aJ4KpltLA" target="_14oWEKoMEee96aJ4KpltLA" source="_vyXbs2KUEeaDbeg_vFJw6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dP0-4KoNEee96aJ4KpltLA"/>
        <condition xmi:type="expression:Expression" xmi:id="_dP0-4aoNEee96aJ4KpltLA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g1Z-cKoNEee96aJ4KpltLA" target="_8QX7QKoMEee96aJ4KpltLA" source="_14oWEKoMEee96aJ4KpltLA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g1Z-caoNEee96aJ4KpltLA"/>
        <condition xmi:type="expression:Expression" xmi:id="_g1Z-cqoNEee96aJ4KpltLA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hpwzkKoNEee96aJ4KpltLA" target="_UzHRQKoNEee96aJ4KpltLA" source="_8QX7QKoMEee96aJ4KpltLA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hpwzkaoNEee96aJ4KpltLA"/>
        <condition xmi:type="expression:Expression" xmi:id="_hpwzkqoNEee96aJ4KpltLA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Rzy14KoMEee96aJ4KpltLA" name="Approver" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_vyXb1WKUEeaDbeg_vFJw6Q"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vyXb1mKUEeaDbeg_vFJw6Q">
        <name xmi:type="expression:Expression" xmi:id="_vyXb12KUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vyXb2GKUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vyXb2WKUEeaDbeg_vFJw6Q">
        <name xmi:type="expression:Expression" xmi:id="_vyXb2mKUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vyXb22KUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vyXb3GKUEeaDbeg_vFJw6Q">
        <name xmi:type="expression:Expression" xmi:id="_vyXb3WKUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vyXb3mKUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vyXb32KUEeaDbeg_vFJw6Q">
        <name xmi:type="expression:Expression" xmi:id="_vyXb4GKUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vyXb4WKUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vyXb4mKUEeaDbeg_vFJw6Q">
        <name xmi:type="expression:Expression" xmi:id="_vyXb42KUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vyXb5GKUEeaDbeg_vFJw6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_vyXb5WKUEeaDbeg_vFJw6Q" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_vyXb5mKUEeaDbeg_vFJw6Q" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_vyXb52KUEeaDbeg_vFJw6Q" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_vyXb6GKUEeaDbeg_vFJw6Q" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_vyXb6WKUEeaDbeg_vFJw6Q" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_vyXb6mKUEeaDbeg_vFJw6Q" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_vyXb62KUEeaDbeg_vFJw6Q" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_vyXb7GKUEeaDbeg_vFJw6Q" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_vyXb7WKUEeaDbeg_vFJw6Q" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_vyXb7mKUEeaDbeg_vFJw6Q" type="Process" element="_RzyO0KoMEee96aJ4KpltLA" name="wfAgentCommission" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_vyYCwGKUEeaDbeg_vFJw6Q" type="2007" element="_RzyO0aoMEee96aJ4KpltLA">
      <children xmi:type="notation:DecorationNode" xmi:id="_vyYCwWKUEeaDbeg_vFJw6Q" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_vyYCwmKUEeaDbeg_vFJw6Q" type="7001">
        <children xmi:type="notation:Node" xmi:id="_vyYCw2KUEeaDbeg_vFJw6Q" type="3007" element="_Rzy14aoMEee96aJ4KpltLA">
          <children xmi:type="notation:DecorationNode" xmi:id="_vyYCxGKUEeaDbeg_vFJw6Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_vyYCxWKUEeaDbeg_vFJw6Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_vyYCyWKUEeaDbeg_vFJw6Q" type="3002" element="_vyXbs2KUEeaDbeg_vFJw6Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vyYCymKUEeaDbeg_vFJw6Q" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vyYCy2KUEeaDbeg_vFJw6Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vyYCzGKUEeaDbeg_vFJw6Q" x="60" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_15LIoKoMEee96aJ4KpltLA" type="3005" element="_14oWEKoMEee96aJ4KpltLA" fontName=".SF NS Text" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_15MWwKoMEee96aJ4KpltLA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_15LIoaoMEee96aJ4KpltLA" x="148" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8QaXgKoMEee96aJ4KpltLA" type="3027" element="_8QX7QKoMEee96aJ4KpltLA" fontName=".SF NS Text" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8Qa-kKoMEee96aJ4KpltLA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8QaXgaoMEee96aJ4KpltLA" x="316" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UzIfYKoNEee96aJ4KpltLA" type="3003" element="_UzHRQKoNEee96aJ4KpltLA" fontName=".SF NS Text">
              <children xmi:type="notation:DecorationNode" xmi:id="_UzJGcKoNEee96aJ4KpltLA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_UzJGcaoNEee96aJ4KpltLA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UzIfYaoNEee96aJ4KpltLA" x="467" y="78"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_vyYCzWKUEeaDbeg_vFJw6Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_vyYCzmKUEeaDbeg_vFJw6Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_vyYCz2KUEeaDbeg_vFJw6Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_vyYC0GKUEeaDbeg_vFJw6Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vyYC0WKUEeaDbeg_vFJw6Q"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_vyYC0mKUEeaDbeg_vFJw6Q"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_vyYC02KUEeaDbeg_vFJw6Q" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_vyYC1GKUEeaDbeg_vFJw6Q"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_vyYC1WKUEeaDbeg_vFJw6Q"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vyYC1mKUEeaDbeg_vFJw6Q" width="744" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_vyYC12KUEeaDbeg_vFJw6Q"/>
    <edges xmi:type="notation:Connector" xmi:id="_dP2NAKoNEee96aJ4KpltLA" type="4001" element="_dP0X0KoNEee96aJ4KpltLA" source="_vyYCyWKUEeaDbeg_vFJw6Q" target="_15LIoKoMEee96aJ4KpltLA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dP20EKoNEee96aJ4KpltLA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dP3bIKoNEee96aJ4KpltLA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dP2NAaoNEee96aJ4KpltLA" fontName=".SF NS Text"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dP2NAqoNEee96aJ4KpltLA" points="[0, -15, -108, -11]$[85, -29, -23, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dP7skKoNEee96aJ4KpltLA" id="(1.0,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g1algKoNEee96aJ4KpltLA" type="4001" element="_g1Z-cKoNEee96aJ4KpltLA" source="_15LIoKoMEee96aJ4KpltLA" target="_8QaXgKoMEee96aJ4KpltLA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g1bMkKoNEee96aJ4KpltLA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g1bMkaoNEee96aJ4KpltLA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g1algaoNEee96aJ4KpltLA" fontName=".SF NS Text"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g1algqoNEee96aJ4KpltLA" points="[0, -6, -153, -5]$[68, -6, -85, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g1dBwKoNEee96aJ4KpltLA" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g1dBwaoNEee96aJ4KpltLA" id="(0.85,0.58)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hpyBsKoNEee96aJ4KpltLA" type="4001" element="_hpwzkKoNEee96aJ4KpltLA" source="_8QaXgKoMEee96aJ4KpltLA" target="_UzIfYKoNEee96aJ4KpltLA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hpyBs6oNEee96aJ4KpltLA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hpyowKoNEee96aJ4KpltLA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hpyBsaoNEee96aJ4KpltLA" fontName=".SF NS Text"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hpyBsqoNEee96aJ4KpltLA" points="[0, -3, -75, 0]$[81, -3, 6, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hp0d8KoNEee96aJ4KpltLA" id="(1.0,0.56)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hp0d8aoNEee96aJ4KpltLA" id="(0.8,0.5)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_DpZ28KoQEee96aJ4KpltLA" type="Form" element="_Dn3l4KoQEee96aJ4KpltLA" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_D31UgKoQEee96aJ4KpltLA" type="2126" element="_Dn40AKoQEee96aJ4KpltLA">
      <children xmi:type="notation:DecorationNode" xmi:id="_D33wwKoQEee96aJ4KpltLA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_D31UgaoQEee96aJ4KpltLA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_D31UgqoQEee96aJ4KpltLA" fontName=".SF NS Text"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_D31Ug6oQEee96aJ4KpltLA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D31UhKoQEee96aJ4KpltLA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_I8YzgKoQEee96aJ4KpltLA" type="2132" element="_I8UiEKoQEee96aJ4KpltLA" fontName=".SF NS Text">
      <children xmi:type="notation:DecorationNode" xmi:id="_I8YzgqoQEee96aJ4KpltLA" type="5188"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_I8YzgaoQEee96aJ4KpltLA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_PXCtUKoREee96aJ4KpltLA" type="2132" element="_PXBfMKoREee96aJ4KpltLA" fontName=".SF NS Text">
      <children xmi:type="notation:DecorationNode" xmi:id="_PXDUYKoREee96aJ4KpltLA" type="5188"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PXCtUaoREee96aJ4KpltLA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_sWT5AKoREee96aJ4KpltLA" type="2132" element="_sWNLUKoREee96aJ4KpltLA" fontName=".SF NS Text">
      <children xmi:type="notation:DecorationNode" xmi:id="_sWXjYKoREee96aJ4KpltLA" type="5188"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sWVHIKoREee96aJ4KpltLA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_RY1UAKoTEee96aJ4KpltLA" type="2126" element="_RYy3wKoTEee96aJ4KpltLA">
      <children xmi:type="notation:DecorationNode" xmi:id="_RY1UBaoTEee96aJ4KpltLA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_RY1UAaoTEee96aJ4KpltLA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_RY1UAqoTEee96aJ4KpltLA" fontName=".SF NS Text"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_RY1UA6oTEee96aJ4KpltLA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RY1UBKoTEee96aJ4KpltLA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_DpZ28aoQEee96aJ4KpltLA"/>
  </notation:Diagram>
</xmi:XMI>
