<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_M5m1IAJBEeaJSPKMJ4A-Iw" name="wfAgentCommission" author="" bonitaVersion="6.5.0" bonitaModelVersion="6.4.0-005" configId="ACED00057400174D794469616772616D362E342E302D303035362E342E32">
    <elements xmi:type="process:Pool" xmi:id="_M5m1IQJBEeaJSPKMJ4A-Iw" name="wfAgentCommission" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Lane" xmi:id="_M5m1JAJBEeaJSPKMJ4A-Iw" name="wfAgentCommission" actor="_M5m1IgJBEeaJSPKMJ4A-Iw">
        <elements xmi:type="process:StartEvent" xmi:id="_GbAVgMPYEeS11cr5KOnhxQ" name="Start" outgoing="_p87aYAJBEeaJSPKMJ4A-Iw">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_GbAVgcPYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GbAVgsPYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GbAVg8PYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GbAVhMPYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_RnDbsAJBEeaJSPKMJ4A-Iw" name="Commission Approval" outgoing="_q0NnsAJBEeaJSPKMJ4A-Iw" incoming="_p87aYAJBEeaJSPKMJ4A-Iw" actor="_M5m1IgJBEeaJSPKMJ4A-Iw">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_RnWWowJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RnWWoQJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RnWWoAJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RnWWogJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_SydM8AJDEeaJSPKMJ4A-Iw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Syj6oQJDEeaJSPKMJ4A-Iw" name="mdm_context" content="mdm_context" type="TYPE_VARIABLE" returnType="org.talend.mdm.workflow.client.MDMContext">
              <referencedElements xmi:type="process:JavaObjectData" xmi:id="_TR5iAAJDEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
            </leftOperand>
            <operator xmi:type="expression:Operator" xmi:id="_SydM8QJDEeaJSPKMJ4A-Iw" type="JAVA_METHOD" expression="setUpdateUsername">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Syj6oAJDEeaJSPKMJ4A-Iw" name="Set the user for update" content="import org.talend.mdm.workflow.client.MDMContextUser;&#xD;&#xA;&#xD;&#xA;MDMContextUser contextUser = mdm_context.getCurrentUser();&#xD;&#xA;return contextUser.getName();" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:JavaObjectData" xmi:id="_XQBkcAJDEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
            </rightOperand>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_RnWWpgJBEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_RnWWpwJBEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RnWWqAJBEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_RnWWqgJBEeaJSPKMJ4A-Iw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_RnWWqQJBEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_EuO5sAJCEeaJSPKMJ4A-Iw" name="CommissionApproval" nColumn="2">
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_EuO5sQJCEeaJSPKMJ4A-Iw" name="Cancel">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_EuO5sgJCEeaJSPKMJ4A-Iw" line="3"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_EuO5swJCEeaJSPKMJ4A-Iw" name="Reject New Commission&#xD;&#xA;" content="Reject New Commission&#xD;&#xA;" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_EuO5tAJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <actions xmi:type="expression:Operation" xmi:id="_pKhQkAJCEeaJSPKMJ4A-Iw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_pKrBkQJCEeaJSPKMJ4A-Iw" name="mdm_context" content="mdm_context" type="TYPE_VARIABLE" returnType="org.talend.mdm.workflow.client.MDMContext">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_pqaRkAJCEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_pKhQkQJCEeaJSPKMJ4A-Iw" type="JAVA_METHOD" expression="setValue">
                  <inputTypes>java.lang.String</inputTypes>
                </operator>
                <rightOperand xmi:type="expression:Expression" xmi:id="_pKrBkAJCEeaJSPKMJ4A-Iw" name="Set Rejected Status" content="&quot;Agent/CommissionChange/ComChangeStatus#Rejected&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
              </actions>
            </widgets>
            <widgets xmi:type="form:TextInfo" xmi:id="_GqpjEAJCEeaJSPKMJ4A-Iw" name="Agent_Name">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Gq9FHwJCEeaJSPKMJ4A-Iw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_Gq9FFQJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_Gq9FFgJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_Gq9FFAJCEeaJSPKMJ4A-Iw" name="Get Agent Name" content="mdm_context.getValue(&quot;Agent/Firstname&quot;) + &quot; &quot; + mdm_context.getValue(&quot;Agent/Lastname&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_SoQkkAJCEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_Gq9FFwJCEeaJSPKMJ4A-Iw" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_Gq9FGAJCEeaJSPKMJ4A-Iw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_Gq9FGQJCEeaJSPKMJ4A-Iw"/>
                <operator xmi:type="expression:Operator" xmi:id="_Gq9FGgJCEeaJSPKMJ4A-Iw" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_Gq9FGwJCEeaJSPKMJ4A-Iw"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_Gq9FEwJCEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_Gq9FEgJCEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_Gq9FEAJCEeaJSPKMJ4A-Iw" name="Agent Name&#xD;&#xA;" content="Agent Name&#xD;&#xA;" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_Gq9FEQJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextInfo" xmi:id="_U7LpcAJCEeaJSPKMJ4A-Iw" name="Current_CommissionCode">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_U7ekbwJCEeaJSPKMJ4A-Iw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_U7ekZQJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_U7ekZgJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_U7ekZAJCEeaJSPKMJ4A-Iw" name="Get Current Commission Code" content="mdm_context.getValue(&quot;Agent/CommissionCode&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_cvZzsAJCEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_U7ekZwJCEeaJSPKMJ4A-Iw" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_U7ekaAJCEeaJSPKMJ4A-Iw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_U7ekaQJCEeaJSPKMJ4A-Iw"/>
                <operator xmi:type="expression:Operator" xmi:id="_U7ekagJCEeaJSPKMJ4A-Iw" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_U7ekawJCEeaJSPKMJ4A-Iw"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_U7ekYwJCEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_U7ekYgJCEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_U7ekYAJCEeaJSPKMJ4A-Iw" name="Current Commission Code" content="Current Commission Code" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_U7ekYQJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextInfo" xmi:id="_d0P74AJCEeaJSPKMJ4A-Iw" name="New_CommissionCode">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d0P78AJCEeaJSPKMJ4A-Iw" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_d0P75gJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_d0P75wJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d0P75QJCEeaJSPKMJ4A-Iw" name="Get New Commission Code" content="mdm_context.getValue(&quot;Agent/CommissionChange/ComChangeCode&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_lMTukAJCEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_d0P76AJCEeaJSPKMJ4A-Iw" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_d0P76QJCEeaJSPKMJ4A-Iw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d0P76gJCEeaJSPKMJ4A-Iw"/>
                <operator xmi:type="expression:Operator" xmi:id="_d0P76wJCEeaJSPKMJ4A-Iw" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d0P77AJCEeaJSPKMJ4A-Iw"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_d0P75AJCEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_d0P74wJCEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d0P74QJCEeaJSPKMJ4A-Iw" name="Review New Commission Code&#xD;&#xA;" content="Review New Commission Code&#xD;&#xA;" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d0P74gJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_2QY6oAJCEeaJSPKMJ4A-Iw" name="Allow">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_2QY6swJCEeaJSPKMJ4A-Iw" line="3" column="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_2QY6pgJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_2QY6pwJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_2QY6pQJCEeaJSPKMJ4A-Iw" name="" content=""/>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_2QY6qAJCEeaJSPKMJ4A-Iw" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_2QY6qQJCEeaJSPKMJ4A-Iw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_2QY6qgJCEeaJSPKMJ4A-Iw"/>
                <operator xmi:type="expression:Operator" xmi:id="_2QY6qwJCEeaJSPKMJ4A-Iw" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_2QY6rAJCEeaJSPKMJ4A-Iw"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_2QY6pAJCEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_2QY6owJCEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_2QY6oQJCEeaJSPKMJ4A-Iw" name="Approve New Commission&#xD;&#xA;" content="Approve New Commission&#xD;&#xA;" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_2QY6ogJCEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <actions xmi:type="expression:Operation" xmi:id="_2l2NQAJCEeaJSPKMJ4A-Iw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_2mJIMQJCEeaJSPKMJ4A-Iw" name="mdm_context" content="mdm_context" type="TYPE_VARIABLE" returnType="org.talend.mdm.workflow.client.MDMContext">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_2_n_MAJCEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_2l2NQQJCEeaJSPKMJ4A-Iw" type="JAVA_METHOD" expression="setValue">
                  <inputTypes>java.lang.String</inputTypes>
                </operator>
                <rightOperand xmi:type="expression:Expression" xmi:id="_2mJIMAJCEeaJSPKMJ4A-Iw" name="Set Approved Status" content="&quot;Agent/CommissionChange/ComChangeStatus#Approved&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
              </actions>
              <actions xmi:type="expression:Operation" xmi:id="_-flJoAJCEeaJSPKMJ4A-Iw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_-fu6oQJCEeaJSPKMJ4A-Iw" name="mdm_context" content="mdm_context" type="TYPE_VARIABLE" returnType="org.talend.mdm.workflow.client.MDMContext">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_-_xFkAJCEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_-flJoQJCEeaJSPKMJ4A-Iw" type="JAVA_METHOD" expression="setValue">
                  <inputTypes>java.lang.String</inputTypes>
                </operator>
                <rightOperand xmi:type="expression:Expression" xmi:id="_-fu6oAJCEeaJSPKMJ4A-Iw" name="Set New Commission Code" content="&quot;Agent/CommissionCode#&quot; + mdm_context.getValue(&quot;Agent/CommissionChange/ComChangeCode&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_BjYR0AJDEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
                </rightOperand>
              </actions>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_EuO5tQJCEeaJSPKMJ4A-Iw" name="Commission Approval" content="Commission Approval" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_RnWWpAJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_RnWWpQJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_YUyfAAJBEeaJSPKMJ4A-Iw" name="Submit Update" outgoing="_rkWEIAJBEeaJSPKMJ4A-Iw" incoming="_q0NnsAJBEeaJSPKMJ4A-Iw">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_YU8QAQJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YUyfAgJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YUyfAQJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YU8QAAJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_h8kmsAJDEeaJSPKMJ4A-Iw" name="Submit Update" definitionId="TalendMDMContextConnector" event="ON_FINISH" definitionVersion="6.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_h8kmsQJDEeaJSPKMJ4A-Iw" definitionId="TalendMDMContextConnector" version="6.0" modelVersion="6.5.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_h8kmsgJDEeaJSPKMJ4A-Iw" key="contextName">
                <expression xmi:type="expression:Expression" xmi:id="_h8kmswJDEeaJSPKMJ4A-Iw" name="mdm_context" content="mdm_context" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_h8kmtAJDEeaJSPKMJ4A-Iw" key="endpointUrl">
                <expression xmi:type="expression:Expression" xmi:id="_h8kmtQJDEeaJSPKMJ4A-Iw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_h8kmtgJDEeaJSPKMJ4A-Iw" key="user">
                <expression xmi:type="expression:Expression" xmi:id="_h8kmtwJDEeaJSPKMJ4A-Iw" name="administrator" content="administrator" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_h8kmuAJDEeaJSPKMJ4A-Iw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_h8kmuQJDEeaJSPKMJ4A-Iw" name="administrator" content="administrator" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_h8kmugJDEeaJSPKMJ4A-Iw" key="partial">
                <expression xmi:type="expression:Expression" xmi:id="_h8kmuwJDEeaJSPKMJ4A-Iw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_h8kmvAJDEeaJSPKMJ4A-Iw" key="overwrite">
                <expression xmi:type="expression:Expression" xmi:id="_h8kmvQJDEeaJSPKMJ4A-Iw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_h8kmvgJDEeaJSPKMJ4A-Iw" key="key">
                <expression xmi:type="expression:Expression" xmi:id="_h8kmvwJDEeaJSPKMJ4A-Iw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_h8kmwAJDEeaJSPKMJ4A-Iw" key="pivot">
                <expression xmi:type="expression:Expression" xmi:id="_h8kmwQJDEeaJSPKMJ4A-Iw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_h8kmwgJDEeaJSPKMJ4A-Iw" key="position">
                <expression xmi:type="expression:Expression" xmi:id="_h8kmwwJDEeaJSPKMJ4A-Iw" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YU8QAgJBEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YU8QAwJBEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YU8QBAJBEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YU8QBgJBEeaJSPKMJ4A-Iw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YU8QBQJBEeaJSPKMJ4A-Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_aj-6cAJBEeaJSPKMJ4A-Iw" name="End1" incoming="_rkWEIAJBEeaJSPKMJ4A-Iw">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_aj-6dAJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aj-6cgJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aj-6cQJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aj-6cwJBEeaJSPKMJ4A-Iw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_MPCjQAJDEeaJSPKMJ4A-Iw" path="_M5m1IQJBEeaJSPKMJ4A-Iw/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_GbAVkcPYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_GbAVksPYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_MPCjRAJDEeaJSPKMJ4A-Iw" path="_M5m1IQJBEeaJSPKMJ4A-Iw/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_MPCjQQJDEeaJSPKMJ4A-Iw" path="_M5m1IQJBEeaJSPKMJ4A-Iw/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_MPCjRQJDEeaJSPKMJ4A-Iw" path="_M5m1IQJBEeaJSPKMJ4A-Iw/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_MPCjQgJDEeaJSPKMJ4A-Iw" path="_M5m1IQJBEeaJSPKMJ4A-Iw/html/consultation.html"/>
      <data xmi:type="process:JavaObjectData" xmi:id="_M5m1OAJBEeaJSPKMJ4A-Iw" name="mdm_context" dataType="_GbAVsMPYEeS11cr5KOnhxQ" className="org.talend.mdm.workflow.client.MDMContext"/>
      <confirmationTemplate xmi:type="process:AssociatedFile" xmi:id="_MPCjQwJDEeaJSPKMJ4A-Iw" path="_M5m1IQJBEeaJSPKMJ4A-Iw/html/confirmation.html"/>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_GbAVk8PYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_GbAVlMPYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_GbAVlcPYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_GbAVlsPYEeS11cr5KOnhxQ" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_p87aYAJBEeaJSPKMJ4A-Iw" source="_GbAVgMPYEeS11cr5KOnhxQ" target="_RnDbsAJBEeaJSPKMJ4A-Iw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_p87aYQJBEeaJSPKMJ4A-Iw"/>
        <condition xmi:type="expression:Expression" xmi:id="_p87aYgJBEeaJSPKMJ4A-Iw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_q0NnsAJBEeaJSPKMJ4A-Iw" source="_RnDbsAJBEeaJSPKMJ4A-Iw" target="_YUyfAAJBEeaJSPKMJ4A-Iw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_q0NnsQJBEeaJSPKMJ4A-Iw"/>
        <condition xmi:type="expression:Expression" xmi:id="_q0NnsgJBEeaJSPKMJ4A-Iw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rkWEIAJBEeaJSPKMJ4A-Iw" source="_YUyfAAJBEeaJSPKMJ4A-Iw" target="_aj-6cAJBEeaJSPKMJ4A-Iw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rkWEIQJBEeaJSPKMJ4A-Iw"/>
        <condition xmi:type="expression:Expression" xmi:id="_rkWEIgJBEeaJSPKMJ4A-Iw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_M5m1IgJBEeaJSPKMJ4A-Iw" name="Approver"/>
      <actors xmi:type="process:Actor" xmi:id="_M5m1IwJBEeaJSPKMJ4A-Iw" name="Requester" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GbAVm8PYEeS11cr5KOnhxQ">
        <name xmi:type="expression:Expression" xmi:id="_GbAVnMPYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GbAVncPYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GbAVnsPYEeS11cr5KOnhxQ">
        <name xmi:type="expression:Expression" xmi:id="_GbAVn8PYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GbAVoMPYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GbAVocPYEeS11cr5KOnhxQ">
        <name xmi:type="expression:Expression" xmi:id="_GbAVosPYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GbAVo8PYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GbAVpMPYEeS11cr5KOnhxQ">
        <name xmi:type="expression:Expression" xmi:id="_GbAVpcPYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GbAVpsPYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GbAVp8PYEeS11cr5KOnhxQ">
        <name xmi:type="expression:Expression" xmi:id="_GbAVqMPYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GbAVqcPYEeS11cr5KOnhxQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_GbAVqsPYEeS11cr5KOnhxQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_GbAVq8PYEeS11cr5KOnhxQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_GbAVrMPYEeS11cr5KOnhxQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_GbAVrcPYEeS11cr5KOnhxQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_GbAVrsPYEeS11cr5KOnhxQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_GbAVr8PYEeS11cr5KOnhxQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_GbAVsMPYEeS11cr5KOnhxQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_GbAVscPYEeS11cr5KOnhxQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_GbAVssPYEeS11cr5KOnhxQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_GbAVs8PYEeS11cr5KOnhxQ" type="Process" element="_M5m1IAJBEeaJSPKMJ4A-Iw" name="wfAgentCommission" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_GbAVtMPYEeS11cr5KOnhxQ" type="2007" element="_M5m1IQJBEeaJSPKMJ4A-Iw">
      <children xmi:type="notation:DecorationNode" xmi:id="_GbAVtcPYEeS11cr5KOnhxQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_GbAVtsPYEeS11cr5KOnhxQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_GbAVt8PYEeS11cr5KOnhxQ" type="3007" element="_M5m1JAJBEeaJSPKMJ4A-Iw">
          <children xmi:type="notation:DecorationNode" xmi:id="_GbAVuMPYEeS11cr5KOnhxQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_GbAVucPYEeS11cr5KOnhxQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_GbAVvcPYEeS11cr5KOnhxQ" type="3002" element="_GbAVgMPYEeS11cr5KOnhxQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_GbAVvsPYEeS11cr5KOnhxQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GbAVv8PYEeS11cr5KOnhxQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GbAVwMPYEeS11cr5KOnhxQ" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RnfgkAJBEeaJSPKMJ4A-Iw" type="3005" element="_RnDbsAJBEeaJSPKMJ4A-Iw" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_RnfgkgJBEeaJSPKMJ4A-Iw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RnfgkQJBEeaJSPKMJ4A-Iw" x="157" y="49" width="136" height="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YU8QBwJBEeaJSPKMJ4A-Iw" type="3027" element="_YUyfAAJBEeaJSPKMJ4A-Iw" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_YU8QCQJBEeaJSPKMJ4A-Iw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YU8QCAJBEeaJSPKMJ4A-Iw" x="385" y="53" width="121" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aj-6dQJBEeaJSPKMJ4A-Iw" type="3003" element="_aj-6cAJBEeaJSPKMJ4A-Iw">
              <children xmi:type="notation:DecorationNode" xmi:id="_aj-6dwJBEeaJSPKMJ4A-Iw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_aj-6eAJBEeaJSPKMJ4A-Iw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aj-6dgJBEeaJSPKMJ4A-Iw" x="594" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_GbAVwcPYEeS11cr5KOnhxQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_GbAVwsPYEeS11cr5KOnhxQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_GbAVw8PYEeS11cr5KOnhxQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_GbAVxMPYEeS11cr5KOnhxQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GbAVxcPYEeS11cr5KOnhxQ"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_GbAVxsPYEeS11cr5KOnhxQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_GbAVx8PYEeS11cr5KOnhxQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_GbAVyMPYEeS11cr5KOnhxQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_GbAVycPYEeS11cr5KOnhxQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GbAVysPYEeS11cr5KOnhxQ"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_GbAVy8PYEeS11cr5KOnhxQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_p9FLYAJBEeaJSPKMJ4A-Iw" type="4001" element="_p87aYAJBEeaJSPKMJ4A-Iw" source="_GbAVvcPYEeS11cr5KOnhxQ" target="_RnfgkAJBEeaJSPKMJ4A-Iw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_p9FLYwJBEeaJSPKMJ4A-Iw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_p9FLZAJBEeaJSPKMJ4A-Iw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_p9FLYQJBEeaJSPKMJ4A-Iw"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_p9FLYgJBEeaJSPKMJ4A-Iw" points="[0, -15, -135, 0]$[67, -14, -68, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_p9FLZQJBEeaJSPKMJ4A-Iw" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q0NnswJBEeaJSPKMJ4A-Iw" type="4001" element="_q0NnsAJBEeaJSPKMJ4A-Iw" source="_RnfgkAJBEeaJSPKMJ4A-Iw" target="_YU8QBwJBEeaJSPKMJ4A-Iw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_q0NntgJBEeaJSPKMJ4A-Iw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_q0NntwJBEeaJSPKMJ4A-Iw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_q0NntAJBEeaJSPKMJ4A-Iw"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q0NntQJBEeaJSPKMJ4A-Iw" points="[0, 3, -102, 0]$[92, 3, -10, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_q0gioAJBEeaJSPKMJ4A-Iw" id="(1.0,0.45588235294117646)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_q0gioQJBEeaJSPKMJ4A-Iw" id="(0.08264462809917356,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rkWEIwJBEeaJSPKMJ4A-Iw" type="4001" element="_rkWEIAJBEeaJSPKMJ4A-Iw" source="_YU8QBwJBEeaJSPKMJ4A-Iw" target="_aj-6dQJBEeaJSPKMJ4A-Iw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rkWEJgJBEeaJSPKMJ4A-Iw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rkWEJwJBEeaJSPKMJ4A-Iw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rkWEJAJBEeaJSPKMJ4A-Iw"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rkWEJQJBEeaJSPKMJ4A-Iw" points="[0, 8, -103, 7]$[103, 15, 0, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rkWEKAJBEeaJSPKMJ4A-Iw" id="(1.0,0.48333333333333334)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_Euh0oAJCEeaJSPKMJ4A-Iw" type="Form" element="_EuO5sAJCEeaJSPKMJ4A-Iw" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_EytKAAJCEeaJSPKMJ4A-Iw" type="2126" element="_EuO5sQJCEeaJSPKMJ4A-Iw">
      <children xmi:type="notation:DecorationNode" xmi:id="_EytKBQJCEeaJSPKMJ4A-Iw" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_EytKAQJCEeaJSPKMJ4A-Iw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_EytKAgJCEeaJSPKMJ4A-Iw"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_EytKAwJCEeaJSPKMJ4A-Iw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EytKBAJCEeaJSPKMJ4A-Iw"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_Gq9FHAJCEeaJSPKMJ4A-Iw" type="2132" element="_GqpjEAJCEeaJSPKMJ4A-Iw">
      <children xmi:type="notation:DecorationNode" xmi:id="_Gq9FHgJCEeaJSPKMJ4A-Iw" type="5188"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Gq9FHQJCEeaJSPKMJ4A-Iw"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_U7ekbAJCEeaJSPKMJ4A-Iw" type="2132" element="_U7LpcAJCEeaJSPKMJ4A-Iw">
      <children xmi:type="notation:DecorationNode" xmi:id="_U7ekbgJCEeaJSPKMJ4A-Iw" type="5188"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_U7ekbQJCEeaJSPKMJ4A-Iw"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_d0P77QJCEeaJSPKMJ4A-Iw" type="2132" element="_d0P74AJCEeaJSPKMJ4A-Iw">
      <children xmi:type="notation:DecorationNode" xmi:id="_d0P77wJCEeaJSPKMJ4A-Iw" type="5188"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_d0P77gJCEeaJSPKMJ4A-Iw"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_2QY6rQJCEeaJSPKMJ4A-Iw" type="2126" element="_2QY6oAJCEeaJSPKMJ4A-Iw">
      <children xmi:type="notation:DecorationNode" xmi:id="_2QY6sgJCEeaJSPKMJ4A-Iw" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_2QY6rgJCEeaJSPKMJ4A-Iw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_2QY6rwJCEeaJSPKMJ4A-Iw"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_2QY6sAJCEeaJSPKMJ4A-Iw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2QY6sQJCEeaJSPKMJ4A-Iw"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Euh0oQJCEeaJSPKMJ4A-Iw"/>
  </notation:Diagram>
</xmi:XMI>
